att-comdev/armada

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
OWNERS

* created issue templates
* OWNERS list

[Feature] [Docs] owners-list-and-issue-standards

---

armada/tiller.py

* removed function
**What issue does this pull request address?**: Fixes #6 
@alanmeadows @v1k0d3n

[bug] removing-unused-function

---

.travis.yml
armada/armada.py
armada/chartbuilder.py
armada/k8s.py
armada/logutil.py
armada/tiller.py
tox.ini

* fix lint issues in armada
* enabled travis lint
* check armada install
We want to be able to be pep8 compliant and updated Travis to run proper lint testing.
**What issue does this pull request address?**: Fixes #7 

[bug] fix-pep8-linting-issues

---

Dockerfile
README.md

**Specific reviewers for pull request**: Adding Dockerfile for future Armada work.

feat: adding dockerfile

---

README.md
examples/armada.yaml

last week, openstack-helm renamed common to helm-toolkit
Also updated README with easier virtualenv usage
Documentation update and example fixes

Updated example file

---

.travis.yml
README.md
requirements.txt
scripts/libgit2.sh
tox.ini

* removed pip from requirements.txt
* added bash for libgit install
* updated tox
**What issue does this pull request address?**: Fixes #19 
@alanmeadows @v1k0d3n

[script] installing-libgit2-deps

---

README.md
docs/development/getting-started.rst
scripts/libgit2.sh

* updated README.md
* added getting started guide
Instructions to set up an development environment. 
**What issue does this pull request address?**: Fixes #15
@alanmeadows @v1k0d3n

[docs] getting-started-guide

---

armada/chartbuilder.py

* updated chartbuilder
**What issue does this pull request address?**: Fixes #36 

[feature] chartbuilder-use-branchs-to-deploy

---

README.md
armada/armada.py
scripts/armada

* if no diff we dont upgrade
**What issue does this pull request address?**: Fixes #26 

[feature] check-chart-diff-before-upgrade

---

armada/armada.py
armada/tiller.py
scripts/armada

* clean up will remove charts that are not maintained by the armada yaml
* uninstall chart
**What issue does this pull request address?**: Fixes #33 

[feature] adding-delete-cleanup-functions

---

.gitignore
armada/armada.py
armada/chartbuilder.py
armada/k8s.py
armada/tiller.py
examples/armada.yaml
scripts/armada

* fix multiple release items
* remove old configs in kubernetes
* add skip flags
**What issue does this pull request address?**: Fixes #42 

[feature] adding-pre-post-actions-to-yaml

---

armada/armada.py
examples/armada.yaml

* example section
@alanmeadows

[bug] removing-used-section

---

Dockerfile

**What is the purpose of this pull request?**: Allows the `$USER` variable to be leveraged in the Dockerfile (was currently unused).
**What issue does this pull request address?**: Fixes # N/A
**Notes for reviewers to consider**: N/A
**Specific reviewers for pull request**: @gardlt

allow the user variable to be leveraged

---

Dockerfile

**What is the purpose of this pull request?**:  Consolidate consecutive `RUN` commands.
**What issue does this pull request address?**: It's a slight optimization.
**Specific reviewers for pull request**: @gardlt

[feature] consolidate consecutive RUN commands in Dockerfile

---

requirements.txt

- added requests module to requirements.txt
**What is the purpose of this pull request?**: add missing requests module
**What issue does this pull request address?**: Fixes #57
**Notes for reviewers to consider**: 
@gardlt @theyer

fix missing requests dependency

---

README.rst
docs/source/development/getting-started.rst

- Remove -p and -v flags from README.rst and getting-started.rst docker run commands
- Add 'clone the forked repo' step to getting-started.rst
**What is the purpose of this pull request?**:  Update documentation
**Specific reviewers for pull request**: @gardlt

[docs] Update README.rst and getting-started.rst

---

armada/handlers/armada.py
armada/log.py
armada/shell.py
requirements.txt
server.py

- Add 'oslo.log' package to requirements.txt
- Replace Python logging library with Oslo logging library in server.py
and log.py
- Update iso8601 silencing to default option
**What is the purpose of this pull request?**: To add support for Oslo logging capabilities
**What issue does this pull request address?**: Fixes #53 
**Notes for reviewers to consider**: This is a work in progress and does not yet support configuration files or docker logs.
**Specific reviewers for pull request**: @gardlt

[WIP][Feat] Add support for Oslo logging capabilities

---

armada/handlers/armada.py

* moved prefight to the top of sync to prevent any actions
**What issue does this pull request address?**: Fixes #72 

[bug] preflight-prevent-actions-dep-tiller-states

---

armada/cli/apply.py
armada/handlers/armada.py

* updated pre and post checks
**What issue does this pull request address?**: Fixes #67 
@alanmeadows

[bug] pre-post-not-check-correctly

---

.travis.yml
CODE_OF_CONDUCT.rst
armada/handlers/chartbuilder.py
armada/tests/unit/handlers/test_chartbuilder.py
armada/tests/unit/utils/test_git.py
armada/tests/unit/utils/test_lint.py
armada/tests/unit/utils/test_release.py
armada/utils/git.py
requirements.txt
setup.cfg
test-requirements.txt
tox.ini

added unittest for the utils module
basic unittest set up
What is the purpose of this pull request?:
What issue does this pull request address?: Fixes #
Notes for reviewers to consider:
Specific reviewers for pull request:
@g0r1v3r4 @theyer @drewwalters96

testing-utils-lib

---

docs/source/conf.py
docs/source/development/getting-started.rst
requirements.txt

**What is the purpose of this pull request?**: Update doc theme
**What issue does this pull request address?**:
**Notes for reviewers to consider**: 
run locally with `sphinx-build -b html docs/source/ ./docbuild'
**Specific reviewers for pull request**: 
@gardlt @drewwalters96

Update documentation theme to sphinx_rtd

---

README.rst
docs/source/development/getting-started.rst
docs/source/operations/guide-use-armada.rst
docs/source/operations/index.rst
examples/openstack-helm.yaml

[docs] update readme

---

armada/handlers/armada.py
armada/handlers/tiller.py
hapi/services/tiller_pb2.py
tools/helm-hapi.sh

@gardlt @drewwalters96 @alanmeadows

[Bug] Fixes always passing 'wait' to tiller

---

docs/source/operations/guide-build-armada-yaml.rst

- Change charts_group to chart_group
**What is the purpose of this pull request?**: To update the documentation for creating an Armada yaml.
**Notes for reviewers to consider**: 
**Specific reviewers for pull request**: @gardlt @theyer

[Docs] Update Armada yaml Docs

---

armada/cli/apply.py
armada/handlers/armada.py
armada/handlers/chartbuilder.py
armada/tests/unit/handlers/test_armada.py
armada/tests/unit/handlers/test_chartbuilder.py
armada/tests/unit/utils/test_git.py
armada/utils/git.py

-No longer attempts to ping repo
-Move cloning all repos to preflight
-Only unique repos are cloned now
-Catches any url errors in preflight and raises exception
**What issue does this pull request address?**: Fixes #95 
@gardlt @drewwalters96 @intlabs

Allow Armada to clone OpenStack infra repos

---

armada/cli/apply.py
armada/handlers/tiller.py
examples/simple.yaml

-chart cleanup was never refactored for new yaml format
@gardlt @drewwalters96

Fix chart cleanup bug

---

armada/handlers/chartbuilder.py

-Armada will source a .helmignore file if present for each chart
-Armada will ignore template files if they match a .helmignore
wildcard or exact filename
**What is the purpose of this pull request?**: Add support for ignoring files in .helmignore
**What issue does this pull request address?**: Fixes #13 
@gardlt @drewwalters96

Add support for .helmignore

---

armada/api/armada_controller.py
armada/api/middleware.py
armada/api/server.py
armada/api/tiller_controller.py
armada/conf/default.py
armada/tests/unit/api/test_api.py
docs/source/operations/guide-api.rst
requirements.txt

- Refactor API structure
- Add API support for existing CLI flags
- Add Keystone token and RBAC
**What is the purpose of this pull request?**: To enhance the Armada API and introduce features already present in the CLI.
**What issue does this pull request address?**: Fixes #54 
**Notes for reviewers to consider**: 
**Specific reviewers for pull request**: @gardlt @theyer @sh8121att

[Feat] Add API support for core features

---

entrypoint.sh

**What is the purpose of this pull request?**: The API will not start using the current container image. Server.py moved to the API folder, and entrypoint.sh needs to be updated.
**Specific reviewers for pull request**: @gardlt @theyer

[Bug] Update API Entrypoint

---

armada/handlers/k8s.py
armada/handlers/tiller.py

Revert "Modify upgrade deletion logic to delete by labels"

---

docs/source/commands/apply.rst
docs/source/commands/index.rst
docs/source/commands/tiller.rst
docs/source/commands/validate.rst
docs/source/operations/guide-use-armada.rst

[docs] how to perform updates

---

armada/cli/apply.py
armada/handlers/armada.py
armada/handlers/tiller.py

This allows the use of a standalone tiller service.
**What is the purpose of this pull request?**: This allows users to specify where tiller is.

[feat] Add tiller-host and -port options to apply

---

.dockerignore
Dockerfile
tools/libgit2.sh

**What is the purpose of this pull request?**: To streamline docker image build
I found being able to build from local code to be helpful while working on integration with Promenade.

Use COPY instead of git clone in Dockerfile

---

armada/handlers/armada.py
armada/utils/lint.py
examples/armada-manifest-v1.yaml

- calling object get after vaild doc
**What issue does this pull request address?**: Fixes #128 

[bug] get armada object after valid document

---

armada/handlers/armada.py

[bug] Remove duplciate instantiation of Tiller handler

---

armada/handlers/armada.py
armada/tests/unit/utils/test_git.py
armada/utils/git.py

- remove exception for repo delete

[bug] fixing repo delete except

---

armada/handlers/armada.py
armada/handlers/k8s.py
armada/handlers/tiller.py
armada/tests/unit/handlers/test_armada.py
armada/tests/unit/handlers/test_tiller.py
docs/source/commands/tiller.rst
docs/source/operations/guide-build-armada-yaml.rst
examples/armada-aio.yaml
examples/armada-manifest-v1.yaml

[feat] upgrading daemonsets

---

docs/source/development/getting-started.rst

- Add new build/run instructions
**What is the purpose of this pull request?**: To update the development documentation to include the new build procedure. 
**Specific reviewers for pull request**: @gardlt @theyer

[Docs] Update development guide

---

Dockerfile
README.rst
docs/source/operations/guide-use-armada.rst
entrypoint.sh

**What is the purpose of this pull request?**: optimize the Dockerfile
- Layer consolidation & remove unnecessary build packages
- Shrinks image from 865MB to 370MB
- Exec gunicorn in entrypoint so <ctrl> c works properly
- Run server as unprivileged user instead of root
- doc updates

Dockerfile cleanup
